---
language: python

python:
  - "2.7"

# Use the new container infrastructure
sudo: required

services:
  - docker

before_install:
  # Build CentOS image to verify ansible role there
  - docker build --rm=true --tag=el-6 --file tests/docker/centos-6 .
  - docker build --rm=true --tag=el-7 --file tests/docker/centos-7 .
  # Build Debian images
  - docker build --rm=true --tag=dn-9 --file tests/docker/debian-9 .

install:
  - pip install ansible && ansible --version
  # Rename a target directory
  - ln -sf -T $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/../collectd
  # Create ansible.cfg with correct roles_path
  - printf "[defaults]\nroles_path=$(dirname $TRAVIS_BUILD_DIR)\nhash_behaviour=merge" > ansible.cfg

script:
  # Add container name in inventory file and check syntax of the playbook
  - echo centos-6 >> tests/inventory
  - echo centos-7 >> tests/inventory
  - echo debian-9 >> tests/inventory
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Run container with SSH server
  - docker run -d --privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro --name centos-6 el-6
  - docker run -d --privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro --name centos-7 el-7
  - docker run -d --privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro --name debian-9 dn-9

  # Run playbook
  - ansible-playbook tests/test.yml -i tests/inventory --become

  # Remove containers
  - docker rm -f centos-6 centos-7 debian-9

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
