---

- name: deliver conf.d files
  template:
    src: collectd.conf.inc.j2
    dest: "{{ svc.service.conf }}/{{ item }}.conf"
    owner: "{{ svc.service.owner }}"
    group: "{{ svc.service.owner }}"
    mode: "0640"
  with_items: "{{ svc.plugins.values() | selectattr('file','defined') |  map(attribute='file') | unique | list }}"
  notify: restart collectd

- name: deliver user-defined configuration
  template:
    src:   "{{ item.value.template }}"
    dest:  "{{ svc.service.conf }}/{{ item.key }}.conf"
    owner: "{{ svc.service.owner }}"
    group: "{{ svc.service.owner }}"
    mode: "0640"
  when: item.value.enable | default(false) | bool
  with_dict: "{{ svc.templates }}"
  notify: restart collectd

- name: deliver configuration
  template:
    src: collectd.conf.j2
    dest:  "{{ svc.service.conf }}/../collectd.conf"
    owner: "{{ svc.service.owner }}"
    group: "{{ svc.service.owner }}"
    mode: "0640"
  notify: restart collectd
