---

- name: install packages
  package:
    name: "{{ item }}*"
    update_cache: yes
    state: present
  with_items: "{{ svc.providers.pm.packages | select | list }}"

- name: create *.conf.d folder
  file:
    path: "{{ svc.service.conf }}"
    state: directory

- name: enable autostart on boot
  service:
    name: "{{ svc.service.daemon }}"
    enabled: yes
