---

- name: install packages
  package: name={{ collectd.providers.pkg.delim.join([item, collectd.service.version]) }}*
           state=present
  with_items: "{{ collectd.providers.pkg.packages | select | list }}"

- name: create *.conf.d folder
  file: path={{ collectd.service.conf }} state=directory

- name: enable autostart on boot
  service: name={{ collectd.service.daemon }} enabled=yes
