---

- name: prepare rhel
  include_tasks: redhat/prepare.yml
  when: (ansible_os_family | lower == "redhat")

- name: prepare debian
  import_tasks: debian/prepare.yml
  when: (ansible_os_family | lower == "debian")
  tags: [ prepare ]

- name: install/upgrade prerequisites
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ svc.providers.pm.prerequisites | default([]) }}"
