---

- name: add yum repositories
  yum_repository: name="{{ item.key }}"
                  description="Collectd maintainer repository"
                  file="{{ item.key }}"
                  baseurl="{{ item.value.url }}"
                  gpgkey="{{ item.value['keys'] | join(' ') }}"
                  gpgcheck=yes
                  enabled=yes
  with_dict: "{{ collectd.providers.pkg.repositories }}"

